import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import { CarouselSize } from "@/components/Carousel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chorki - Film Fun Foorti",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />

        <CarouselSize />
        {children}
      </body>
    </html>
  );
}
